
const C={green:'#0d675b',mint:'#bce8dc',red:'#dc6868',ink:'#063b35',yellow:'#f2c94c'},$=s=>document.querySelector(s),pct=(a,b)=>b?Math.round(a/b*100):0,win=m=>m.resultado==='PG',group=(a,k)=>a.reduce((o,x)=>((o[x[k]]??=[]).push(x),o),{}),uniq=a=>[...new Set(a)];let all=[],tournaments=[],charts={};
const centerDiff={id:'centerDiff',afterDraw(chart){if(chart.canvas.id!=='resultChart')return;const {ctx,chartArea:{left,right,top,bottom}}=chart,d=chart.config.options.plugins.centerDiff.value;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=d>=0?C.green:C.red;ctx.font='800 32px Inter,system-ui';ctx.fillText(`${d>=0?'+':''}${d}`,(left+right)/2,(top+bottom)/2-5);ctx.fillStyle='#6b817c';ctx.font='600 11px Inter,system-ui';ctx.fillText('DIFERENCIA',(left+right)/2,(top+bottom)/2+22);ctx.restore()}};Chart.register(centerDiff);
async function init(){[all,tournaments]=await Promise.all(['data/partidos.json','data/torneos.json'].map(x=>fetch(x).then(r=>r.json())));fill();render()}
function fill(){const years=uniq(all.map(x=>x.anio)).sort((a,b)=>b-a);$('#yearFilter').innerHTML='<option value="ALL">Todos</option>'+years.map(x=>`<option>${x}</option>`).join('');$('#formatFilter').innerHTML+=uniq(all.map(x=>x.formato)).sort().map(x=>`<option>${x}</option>`).join('');$('#courtFilter').innerHTML+=uniq(all.map(x=>x.cancha)).sort().map(x=>`<option>${x}</option>`).join('');['yearFilter','formatFilter','courtFilter'].forEach(x=>$('#'+x).onchange=render);$('#resetFilters').onclick=()=>{['yearFilter','formatFilter','courtFilter'].forEach(x=>$('#'+x).value='ALL');render()};const last=[...all].sort((a,b)=>b.fecha.localeCompare(a.fecha))[0];$('#lastMatch').textContent='Último registro: '+date(last.fecha)}
function filtered(){return all.filter(x=>($('#yearFilter').value==='ALL'||String(x.anio)===$('#yearFilter').value)&&($('#formatFilter').value==='ALL'||x.formato===$('#formatFilter').value)&&($('#courtFilter').value==='ALL'||x.cancha===$('#courtFilter').value))}
function render(){const m=filtered();kpis(m);draw(m);partners(m);torneos();insights(m)}
function ranks(m,filter){return Object.entries(group(m,'companiero')).map(([name,v])=>({name,pj:v.length,pg:v.filter(win).length,rate:pct(v.filter(win).length,v.length)})).filter(filter).sort((a,b)=>b.rate-a.rate||b.pj-a.pj)}
function kpis(m){const w=m.filter(win).length,l=m.length-w,ordered=[...m].sort((a,b)=>b.fecha.localeCompare(a.fecha)||b.id-a.id);let n=0,type=ordered[0]?.resultado;for(const x of ordered){if(x.resultado!==type)break;n++}const short=ranks(m,x=>x.pj>=3&&x.pj<=10)[0],long=ranks(m,x=>x.pj>10)[0];const a=[['Partidos jugados',m.length,`${w} ganados · ${l} perdidos`],['Efectividad',pct(w,m.length)+'%','sobre el período filtrado'],['Racha actual',n||0,n?`${type==='PG'?'victorias':'derrotas'} consecutivas`:'sin datos'],['Mejor compañero ≤ 10',short?.name||'—',short?`${short.rate}% en ${short.pj} partidos`:'mínimo 3 partidos'],['Mejor compañero > 10',long?.name||'—',long?`${long.rate}% en ${long.pj} partidos`:'sin compañeros en este rango']];$('#kpis').innerHTML=a.map(x=>`<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}
function opt(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{usePointStyle:true,boxWidth:8,color:C.ink,font:{weight:700}}}},scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,beginAtZero:true,grid:{color:'#e6efeb'}}}}}
function draw(m){Object.values(charts).forEach(x=>x.destroy());charts={};const by=group(m.map(x=>({...x,ym:`${x.anio}-${String(x.mes).padStart(2,'0')}`})),'ym'),keys=Object.keys(by).sort(),months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];charts.month=new Chart($('#monthlyChart'),{type:'bar',data:{labels:keys.map(k=>`${months[+k.slice(5)-1]} ${k.slice(2,4)}`),datasets:[{label:'Ganados',data:keys.map(k=>by[k].filter(win).length),backgroundColor:C.green,borderRadius:5,stack:'partidos'},{label:'Perdidos',data:keys.map(k=>by[k].filter(x=>!win(x)).length),backgroundColor:C.red,borderRadius:5,stack:'partidos'},{type:'line',label:'Efectividad',data:keys.map(k=>pct(by[k].filter(win).length,by[k].length)),borderColor:'#15917d',backgroundColor:'#15917d',pointRadius:4,tension:.35,yAxisID:'y1'}]},options:{...opt(),scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,beginAtZero:true,grid:{color:'#e6efeb'},title:{display:true,text:'Partidos'}},y1:{beginAtZero:true,max:100,position:'right',grid:{display:false},ticks:{callback:v=>v+'%'},title:{display:true,text:'Efectividad'}}}}});const w=m.filter(win).length,l=m.length-w;charts.result=new Chart($('#resultChart'),{type:'doughnut',data:{labels:['Ganados','Perdidos'],datasets:[{data:[w,l],backgroundColor:[C.green,C.red],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom'},centerDiff:{value:w-l}}}});const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'],bd=group(m,'dia');charts.day=new Chart($('#dayChart'),{type:'bar',data:{labels:days.map(x=>x.slice(0,3)),datasets:[{label:'Partidos',data:days.map(x=>(bd[x]||[]).length),backgroundColor:C.green,borderRadius:7}]},options:opt()});const courts=Object.entries(group(m,'cancha')).sort((a,b)=>b[1].length-a[1].length).slice(0,7);charts.court=new Chart($('#courtChart'),{type:'bar',data:{labels:courts.map(x=>x[0]),datasets:[{label:'Partidos',data:courts.map(x=>x[1].length),backgroundColor:C.green,borderRadius:7}]},options:{...opt(),indexAxis:'y'}});const formats=Object.entries(group(m,'formato')).sort((a,b)=>b[1].length-a[1].length);charts.format=new Chart($('#formatChart'),{type:'bar',data:{labels:formats.map(x=>x[0]),datasets:[{label:'Efectividad %',data:formats.map(x=>pct(x[1].filter(win).length,x[1].length)),backgroundColor:C.green,borderRadius:7}]},options:{...opt(),scales:{x:{grid:{display:false}},y:{beginAtZero:true,max:100,ticks:{callback:v=>v+'%'}}}}})}
function partners(m){const r=ranks(m,x=>x.pj>=3).slice(0,8);$('#partnerTable').innerHTML=r.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.pj}</td><td>${x.pg}</td><td><div class="rate"><div class="bar"><i style="width:${x.rate}%"></i></div><b>${x.rate}%</b></div></td></tr>`).join('')||'<tr><td colspan="4">Sin datos suficientes</td></tr>'}
function torneos(){const champs=tournaments.filter(x=>x.puesto==='campeon').length;$('#tournamentSummary').textContent=`${tournaments.length} torneos · ${champs} títulos`;$('#tournamentList').innerHTML=[...tournaments].sort((a,b)=>b.fecha.localeCompare(a.fecha)).map(t=>{const cls=t.puesto==='campeon'?'champion':t.puesto==='subcampeon'?'runner-up':'';const label=t.puesto==='campeon'?'🏆 Campeón':t.puesto==='subcampeon'?'🥈 Subcampeón':stage(t);return`<article class="tournament-item ${cls}"><header><b>${t.organizador}</b><time>${date(t.fecha)}</time></header><p>${t.categoria} · con ${t.companiero}</p><span class="pill">${label}</span></article>`}).join('')}
function stage(t){if(t.final!==null)return'Final';if(t.semifinal!==null)return'Semifinal';if(t.cuartos!==null)return'Cuartos';if(t.octavos!==null)return'Octavos';return t.zona?'Zona':'Fase inicial'}
function insights(m){const calc=k=>Object.entries(group(m,k)).map(([name,v])=>({name,n:v.length,r:pct(v.filter(win).length,v.length)}));const day=calc('dia').filter(x=>x.n>=3).sort((a,b)=>b.r-a.r)[0],mate=calc('companiero').filter(x=>x.n>=5).sort((a,b)=>b.r-a.r||b.n-a.n)[0],court=calc('cancha').sort((a,b)=>b.n-a.n)[0],format=calc('formato').filter(x=>x.n>=3).sort((a,b)=>b.r-a.r)[0];const a=[['📅','Tu mejor día',day?`${day.name}: ${day.r}% en ${day.n} partidos.`:'Sin datos suficientes.'],['🤝','Sociedad destacada',mate?`Con ${mate.name}: ${mate.r}% en ${mate.n} partidos.`:'Sin datos suficientes.'],['📍','Cancha más frecuente',court?`${court.name}: ${court.n} partidos y ${court.r}% de efectividad.`:'Sin datos suficientes.'],['🎾','Formato más efectivo',format?`${format.name}: ${format.r}% en ${format.n} partidos.`:'Sin datos suficientes.']];$('#insightList').innerHTML=a.map(x=>`<div class="insight-row"><div class="icon">${x[0]}</div><div><b>${x[1]}</b><p>${x[2]}</p></div></div>`).join('')}
function date(s){const[y,m,d]=s.split('-');return`${d}/${m}/${y}`}init();
